#%RAML 1.0
title: Projet de session INF5190 API
version: v1
baseUri: http://127.0.0.1/api
mediaType: application/json
documentation:
  - title: Accueil
    content: |
      Bienvenue dans la documentation de l'API du projet de session
      INF5190. Cette API vous permettra d'obtenir une foule d'infos
      sur les installations de la Ville de Montréal.